import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.css";
import { cn } from "../utils";

const openRunde = localFont({
  variable: "--font-open-runde",
  display: "swap",
  src: [
    {
      path: "../styles/fonts/OpenRunde-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../styles/fonts/OpenRunde-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../styles/fonts/OpenRunde-Semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../styles/fonts/OpenRunde-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
});

const sfPro = localFont({
  variable: "--font-sf-pro",
  display: "swap",
  src: [
    {
      path: "../styles/fonts/SFRounded-Medium.woff2",
      weight: "500",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: {
    template: "%s | Proptech Feed",
    default: "Proptech Feed",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("bg-background", openRunde.variable, sfPro.variable)}
    >
      <body className="h-dvh overflow-hidden antialiased">{children}</body>
    </html>
  );
}
